//go:build !ignore_autogenerated

/*
Copyright 2023-2026 YANDEX LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnouncerComp) DeepCopyInto(out *AnnouncerComp) {
	*out = *in
	out.Image = in.Image
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnouncerComp.
func (in *AnnouncerComp) DeepCopy() *AnnouncerComp {
	if in == nil {
		return nil
	}
	out := new(AnnouncerComp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDiscovery) DeepCopyInto(out *AutoDiscovery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDiscovery.
func (in *AutoDiscovery) DeepCopy() *AutoDiscovery {
	if in == nil {
		return nil
	}
	out := new(AutoDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdAdapterComp) DeepCopyInto(out *BirdAdapterComp) {
	*out = *in
	out.Image = in.Image
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdAdapterComp.
func (in *BirdAdapterComp) DeepCopy() *BirdAdapterComp {
	if in == nil {
		return nil
	}
	out := new(BirdAdapterComp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BirdComponent) DeepCopyInto(out *BirdComponent) {
	*out = *in
	out.Image = in.Image
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BirdComponent.
func (in *BirdComponent) DeepCopy() *BirdComponent {
	if in == nil {
		return nil
	}
	out := new(BirdComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoxComponent) DeepCopyInto(out *BoxComponent) {
	*out = *in
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoxComponent.
func (in *BoxComponent) DeepCopy() *BoxComponent {
	if in == nil {
		return nil
	}
	out := new(BoxComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoxComponents) DeepCopyInto(out *BoxComponents) {
	*out = *in
	if in.Controlplane != nil {
		in, out := &in.Controlplane, &out.Controlplane
		*out = new(BoxComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Dataplane != nil {
		in, out := &in.Dataplane, &out.Dataplane
		*out = new(BoxComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Bird != nil {
		in, out := &in.Bird, &out.Bird
		*out = new(BoxComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.BirdAdapter != nil {
		in, out := &in.BirdAdapter, &out.BirdAdapter
		*out = new(BoxComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.Announcer != nil {
		in, out := &in.Announcer, &out.Announcer
		*out = new(BoxComponent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoxComponents.
func (in *BoxComponents) DeepCopy() *BoxComponents {
	if in == nil {
		return nil
	}
	out := new(BoxComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoxOperator) DeepCopyInto(out *BoxOperator) {
	*out = *in
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoxOperator.
func (in *BoxOperator) DeepCopy() *BoxOperator {
	if in == nil {
		return nil
	}
	out := new(BoxOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BoxType) DeepCopyInto(out *BoxType) {
	*out = *in
	in.Components.DeepCopyInto(&out.Components)
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make(map[string]BoxOperator, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BoxType.
func (in *BoxType) DeepCopy() *BoxType {
	if in == nil {
		return nil
	}
	out := new(BoxType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsSpec) DeepCopyInto(out *ComponentsSpec) {
	*out = *in
	in.Controlplane.DeepCopyInto(&out.Controlplane)
	in.Dataplane.DeepCopyInto(&out.Dataplane)
	if in.Bird != nil {
		in, out := &in.Bird, &out.Bird
		*out = new(BirdComponent)
		(*in).DeepCopyInto(*out)
	}
	if in.BirdAdapter != nil {
		in, out := &in.BirdAdapter, &out.BirdAdapter
		*out = new(BirdAdapterComp)
		(*in).DeepCopyInto(*out)
	}
	if in.Announcer != nil {
		in, out := &in.Announcer, &out.Announcer
		*out = new(AnnouncerComp)
		(*in).DeepCopyInto(*out)
	}
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make([]OperatorSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsSpec.
func (in *ComponentsSpec) DeepCopy() *ComponentsSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSource.
func (in *ConfigSource) DeepCopy() *ConfigSource {
	if in == nil {
		return nil
	}
	out := new(ConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlplaneSpec) DeepCopyInto(out *ControlplaneSpec) {
	*out = *in
	out.Image = in.Image
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		**out = **in
	}
	if in.Numa != nil {
		in, out := &in.Numa, &out.Numa
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlplaneSpec.
func (in *ControlplaneSpec) DeepCopy() *ControlplaneSpec {
	if in == nil {
		return nil
	}
	out := new(ControlplaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataplaneSpec) DeepCopyInto(out *DataplaneSpec) {
	*out = *in
	out.Image = in.Image
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		**out = **in
	}
	if in.Hugepages != nil {
		in, out := &in.Hugepages, &out.Hugepages
		*out = new(Hugepages)
		**out = **in
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataplaneSpec.
func (in *DataplaneSpec) DeepCopy() *DataplaneSpec {
	if in == nil {
		return nil
	}
	out := new(DataplaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hugepages) DeepCopyInto(out *Hugepages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hugepages.
func (in *Hugepages) DeepCopy() *Hugepages {
	if in == nil {
		return nil
	}
	out := new(Hugepages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRef) DeepCopyInto(out *ImageRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRef.
func (in *ImageRef) DeepCopy() *ImageRef {
	if in == nil {
		return nil
	}
	out := new(ImageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagesSpec) DeepCopyInto(out *ImagesSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagesSpec.
func (in *ImagesSpec) DeepCopy() *ImagesSpec {
	if in == nil {
		return nil
	}
	out := new(ImagesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedPatch) DeepCopyInto(out *NamedPatch) {
	*out = *in
	in.Patch.DeepCopyInto(&out.Patch)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedPatch.
func (in *NamedPatch) DeepCopy() *NamedPatch {
	if in == nil {
		return nil
	}
	out := new(NamedPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.Deployments != nil {
		in, out := &in.Deployments, &out.Deployments
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorContainer) DeepCopyInto(out *OperatorContainer) {
	*out = *in
	out.Image = in.Image
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigSource)
		**out = **in
	}
	if in.HostIPC != nil {
		in, out := &in.HostIPC, &out.HostIPC
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorContainer.
func (in *OperatorContainer) DeepCopy() *OperatorContainer {
	if in == nil {
		return nil
	}
	out := new(OperatorContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorSpec) DeepCopyInto(out *OperatorSpec) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]OperatorContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorSpec.
func (in *OperatorSpec) DeepCopy() *OperatorSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncStatus) DeepCopyInto(out *SyncStatus) {
	*out = *in
	if in.Synced != nil {
		in, out := &in.Synced, &out.Synced
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutOfSync != nil {
		in, out := &in.OutOfSync, &out.OutOfSync
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SyncWaiting != nil {
		in, out := &in.SyncWaiting, &out.SyncWaiting
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncStatus.
func (in *SyncStatus) DeepCopy() *SyncStatus {
	if in == nil {
		return nil
	}
	out := new(SyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetComponentOverride) DeepCopyInto(out *YanetComponentOverride) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make(map[string]ImageRef, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetComponentOverride.
func (in *YanetComponentOverride) DeepCopy() *YanetComponentOverride {
	if in == nil {
		return nil
	}
	out := new(YanetComponentOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetComponentsOverride) DeepCopyInto(out *YanetComponentsOverride) {
	*out = *in
	if in.Controlplane != nil {
		in, out := &in.Controlplane, &out.Controlplane
		*out = new(YanetComponentOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Dataplane != nil {
		in, out := &in.Dataplane, &out.Dataplane
		*out = new(YanetComponentOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Bird != nil {
		in, out := &in.Bird, &out.Bird
		*out = new(YanetComponentOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.BirdAdapter != nil {
		in, out := &in.BirdAdapter, &out.BirdAdapter
		*out = new(YanetComponentOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Announcer != nil {
		in, out := &in.Announcer, &out.Announcer
		*out = new(YanetComponentOverride)
		(*in).DeepCopyInto(*out)
	}
	if in.Operators != nil {
		in, out := &in.Operators, &out.Operators
		*out = make(map[string]YanetComponentOverride, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetComponentsOverride.
func (in *YanetComponentsOverride) DeepCopy() *YanetComponentsOverride {
	if in == nil {
		return nil
	}
	out := new(YanetComponentsOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetConfigCustomValidator) DeepCopyInto(out *YanetConfigCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetConfigCustomValidator.
func (in *YanetConfigCustomValidator) DeepCopy() *YanetConfigCustomValidator {
	if in == nil {
		return nil
	}
	out := new(YanetConfigCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetConfigSpec) DeepCopyInto(out *YanetConfigSpec) {
	*out = *in
	out.AutoDiscovery = in.AutoDiscovery
	in.Images.DeepCopyInto(&out.Images)
	in.Components.DeepCopyInto(&out.Components)
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]NamedPatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BoxTypes != nil {
		in, out := &in.BoxTypes, &out.BoxTypes
		*out = make([]BoxType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetConfigSpec.
func (in *YanetConfigSpec) DeepCopy() *YanetConfigSpec {
	if in == nil {
		return nil
	}
	out := new(YanetConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetConfigStatus) DeepCopyInto(out *YanetConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetConfigStatus.
func (in *YanetConfigStatus) DeepCopy() *YanetConfigStatus {
	if in == nil {
		return nil
	}
	out := new(YanetConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetConfigV2) DeepCopyInto(out *YanetConfigV2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetConfigV2.
func (in *YanetConfigV2) DeepCopy() *YanetConfigV2 {
	if in == nil {
		return nil
	}
	out := new(YanetConfigV2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YanetConfigV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetConfigV2List) DeepCopyInto(out *YanetConfigV2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]YanetConfigV2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetConfigV2List.
func (in *YanetConfigV2List) DeepCopy() *YanetConfigV2List {
	if in == nil {
		return nil
	}
	out := new(YanetConfigV2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YanetConfigV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetSpec) DeepCopyInto(out *YanetSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AutoSync != nil {
		in, out := &in.AutoSync, &out.AutoSync
		*out = new(bool)
		**out = **in
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = new(YanetComponentsOverride)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetSpec.
func (in *YanetSpec) DeepCopy() *YanetSpec {
	if in == nil {
		return nil
	}
	out := new(YanetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetStatus) DeepCopyInto(out *YanetStatus) {
	*out = *in
	if in.Pods != nil {
		in, out := &in.Pods, &out.Pods
		*out = make(map[v1.PodPhase][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	in.Sync.DeepCopyInto(&out.Sync)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodesStatus != nil {
		in, out := &in.NodesStatus, &out.NodesStatus
		*out = make(map[string]NodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetStatus.
func (in *YanetStatus) DeepCopy() *YanetStatus {
	if in == nil {
		return nil
	}
	out := new(YanetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetV2) DeepCopyInto(out *YanetV2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetV2.
func (in *YanetV2) DeepCopy() *YanetV2 {
	if in == nil {
		return nil
	}
	out := new(YanetV2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YanetV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YanetV2List) DeepCopyInto(out *YanetV2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]YanetV2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YanetV2List.
func (in *YanetV2List) DeepCopy() *YanetV2List {
	if in == nil {
		return nil
	}
	out := new(YanetV2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *YanetV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
