apiVersion: yanet.yanet-platform.io/v1alpha1
kind: YanetConfig
metadata:
  name: config
  namespace: yanet
spec:
  additionalopts:
    annotations:
    - annotations:
        telegraf.influxdata.com/ports: "8080"
      name: telegraf
    - annotations:
        checkpointer.ydb.tech/checkpoint: "true"
        checkpointer.ydb.tech/manual-recovery: "true"
      name: checkpointer
    initcontainers:
    - args:
      - -c
      - echo hello
      command:
      - /bin/bash
      image: busybox
      name: test
    poststart:
    - exec: sleep 60; /bin/mountpoint -q /etc/yanet/controlplane.conf; /bin/mount
        -o ro,bind /etc/yanet/controlplane.slb.conf /etc/yanet/controlplane.conf;/usr/bin/yanet-cli
        reload 2>&1 >> /reloader.log
      name: reloader
    - exec: apt-get install -y jq iproute2; until ip addr | grep kni[0-9]; do sleep 2; done; cat /etc/yanet/controlplane.conf | jq -j '.modules.route0.interfaces | keys[] as $k | (.[$k].ipAddresses)[] as $ip | $k, " ", $ip, "\n"' | grep kni | while read iface addr;do ip link add link $(echo $iface | cut -d\. -f1) name $iface type vlan id $(echo $iface | cut -d\. -f2) || true; ip $(if grep -q "::" <<< $ip; then echo "-6";echo "-4";fi) addr add $addr dev $iface || true; done 2>&1 >> /netconfig.log
      name: netconfig
  autodiscovery:
    enable: false
    namespace: yanet
    registry: dockerhub.io
  enabledopts:
    balancer:
      dataplane:
        hostipc: true
        limits:
          hugepages-1Gi: 90Gi
          memory: 128Gi
        poststart:
          exec:
          - reloader
          - netconfig
        annotations:
        - checkpointer
      controlplane:
        annotations:
        - checkpointer
      bird:
        annotations:
        - checkpointer
      announcer:
        annotations:
        - checkpointer
    release:
      dataplane:
        initcontainers:
        - test
        poststart:
          exec:
          - netconfig
        annotations:
        - checkpointer
      controlplane:
        annotations:
        - telegraf
        - checkpointer
      bird:
        annotations:
        - checkpointer
      announcer:
        annotations:
        - checkpointer
  stop: false
  updatewindow: 10
