replicaCount: 2

image:
  repository: yanet-platform/yanet-operator
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "yanet-operator"

serviceAccount:
  name: "controller-manager"

podAnnotations: {}

hostNetwork: false

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
     cpu: 2
     memory: 2Gi

tolerations: []
nodeSelector: {}

affinity: {}

yanetconfig:
  spec:
    autodiscovery:
      enable: false
      namespace: yanet
      registry: dockerhub.io
    stop: false

extraManifests: {}
