{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yanet-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yanet-operator.labels" . | nindent 4 }}
    release: {{ .Values.metrics.serviceMonitor.release }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
  jobLabel: {{ include "yanet-operator.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "yanet-operator.selectorLabels" . | nindent 6 }}
{{- end }}
