{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "yanet-operator.fullname" . }}-validating-webhook-configuration
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "yanet-operator.fullname" . }}-webhook-cert
  {{- end }}
  labels:
    {{- include "yanet-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "yanet-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-yanet-yanet-platform-io-v1alpha1-yanet
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  matchPolicy: Exact
  name: vyanet.kb.io
  rules:
  - apiGroups:
    - yanet.yanet-platform.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - yanets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "yanet-operator.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-yanet-yanet-platform-io-v1alpha1-yanetconfig
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  matchPolicy: Exact
  name: vyanetconfig.kb.io
  rules:
  - apiGroups:
    - yanet.yanet-platform.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - yanetconfigs
  sideEffects: None
{{- end }}
